name: Scheduled LinkedIn Job Scraper

on:
  schedule:
    - cron: '0 */12 * * *'   # Every 12 hours
  workflow_dispatch:         # Allow manual runs

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install linkedin-jobs-scraper pandas

    - name: Run the LinkedIn job scraper
      run: python webscrapping_projects/scheduled/linkedin_lib_de_fil.py

    - name: Commit and push results
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add webscrapping_projects/scheduled/outputs/jobs_log.csv
        git commit -m "Update job log - $(date -u)"
        git push
      continue-on-error: true  # Prevent failure if there's no change
