name: Scheduled LinkedIn Job Scraper

on:
  schedule:
    - cron: '0 6,18 * * *'   # Every 12 hours
  workflow_dispatch:         # Allow manual runs

permissions:
  contents: write

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install linkedin-jobs-scraper pandas

    - name: Run the LinkedIn job scraper
      run: python webscrapping_projects/scheduled/linkedin_lib_de_fil.py

    - name: Commit and push results
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git stash --include-untracked
        git pull --rebase origin LinkedIn_auto_scrapper
        git stash pop
        git add webscrapping_projects/scheduled/outputs/jobs_log.tsv
        git commit -m "Update job log - $(date -u)" || echo "No changes to commit"
        git push https://x-access-token:${GH_PAT}@github.com/mugundanaswin/Data_Engineering.git HEAD:LinkedIn_auto_scrapper
